# W&B organization
WANDB_MODE: "online" # Disabled / online
ENTITY: ""
PROJECT: "RP-AdamLMCDQN"
TAGS: ["DQN"]

ENV_NAME: "GaussianBandit-bsuite"

# Algorithm commons
NUM_ENVS: 10
BUFFER_SIZE: 10000
BUFFER_BATCH_SIZE: 128
TOTAL_TIMESTEPS: 5.0e+5
TARGET_UPDATE_INTERVAL: 500
LR: 2.5e-4
LEARNING_STARTS: 10000
TRAINING_INTERVAL: 10
GAMMA: 0.99
TAU: 1.0
SEED: 42
NUM_SEEDS: 5

# E-greedy parameters
EPSILON_START: 1.0
EPSILON_FINISH: 0.05
EPSILON_ANNEAL_TIME: 25.0e+4
LR_LINEAR_DECAY: false

# Adam LMCDQN parameters
alpha1: 0.9
alpha2: 0.999
eps: 1.0e-8
inverse_temperature: 10.0e+4
J: 10
a: 0.1

# Experiment parameters
EXPERIMENT_NAME: "Bias Factor A try"
